### ISSUE TITLE
Duplicated gu- styles in demo-elem necessary?

### ISSUE THREAD

**Issue by shawncplus** [ergo/polymer-dragula#2]
In the demo-elem demo for nested drag the demo-elem has the gu-* styles copied from the polymer-dragula element itself, are these necessary or accidentally included?

**Comment by ergo** [comment]
I think so, because the "dragged" elem leaks outside shadow dom - by default it is attached to window.document. Maybe we can improve on that.

**Comment by shawncplus** [comment]
Yeah if that's the case maybe encapsulate those into a dragula-styles element to allow easy usage?
